modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Save%20and%20Load%20Inventories"
logoFile="icon.png"

[[mods]]
modId="saveandloadinventories"
version="3.3"
displayName="Save and Load Inventories"
displayURL="https://serilum.com/mod/save-and-load-inventories"
authors="Rick South"
description='''Easily save and load inventories by using commands.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Alister, Andrean Olgo, aternosorg, BirdieMiner, Cherriesaurus, Jack, Jeremy Langford, Michael W. S., pepe1191, Shana Gitnick, Tyler Behl   

If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''

[[dependencies.saveandloadinventories]]
    modId="collective"
    mandatory=true
    versionRange="[7.54,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.saveandloadinventories]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.6]"
    ordering="NONE"
    side="BOTH"
